version: "3.8"
services:
    # PHP service
    app:
        build: .
        container_name: integration_app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network
    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: integration_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge